name: trans
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  flutter_map: ^6.0.0
  latlong2: ^0.9.0
  geolocator: ^13.0.0
  supabase_flutter: ^2.0.0
  qr_flutter: ^4.1.0
  intl: ^0.19.0
  sliding_up_panel: ^2.0.0+1
  flutter_dotenv: ^5.1.0
  
  # NEW PACKAGES
  shared_preferences: ^2.2.0
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - lib/assets/